export interface MissionForm {
    country: string,
    city: string,
    title: string,
    description: string,
    organisationName: string,
    organisationDetails: string,
    startDate: Date|null,
    endDate: Date|null,
    totalSeats: number,
    registrationDeadline: Date|null,
    theme: string,
    skills: string[],
    // images: File[],
    // documents: File[],
    availability: number,
    missionType: number,
    goal: string|null,
}